### PR TITLE
Completed incomplete fix for baseband_xmm_power wakelock 

### PR DESCRIPTION
**Pull request by micw**
Completed incomplete fix for baseband_xmm_power wakelock  on Nexus 7 G (Tilapia).

For details see http://www.android-hilfe.de/thema/kernel-root-3g-workaround-fuer-android-os-bug-baseband_xmm_power-wakelock.666283
This patch disables the wakelock completely by default.
If you use 3G and have any instabilities, flash the activator script from
http://www.android-hilfe.de/thema/kernel-root-3g-workaround-fuer-android-os-bug-baseband_xmm_power-wakelock.666283/#post-8668699
which will re-enable the wakelock but times it out after 10 seconds.

### CODE REVIEW

**Comment by micw** [comment]
Thank you a lot. I run a build of this kernel on my tilapia since yesterday with your cm release - 95% battery left after 20h!

**Comment by GtrCraft** [comment]
Yeah sorry, I forgot you had a pull request. I will add it to my other grouper kernel too

**Comment by micw** [comment]
I'd also like to add support for tilapia to your cm13 flash script (so that users do not need to unzip/change/zip the whole cm13 build) - but I cannot find it in your repo. Any hints?

**Comment by GtrCraft** [comment]
I recommend using grouper's twrp over build.prop edits. And the scripts are not being made in the device tree

**Comment by micw** [comment]
I have no idea what that means ;-)
But simply changing the script seems very easy to me.

**Comment by GtrCraft** [comment]
Flash twrp of grouper and done

**Pull request merged**
